ARG NODE_VERSION=16

FROM node:$NODE_VERSION-buster

WORKDIR /app
RUN yarn global add lerna
COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap

CMD yarn dev --scope=server
