ARG NODE_VERSION=16

FROM node:$NODE_VERSION-buster
ENV NODE_ENV development
WORKDIR /app

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=client

CMD yarn preview --scope=client
